owner: "jdubois-chevalier"
remote_repository_url: "https://github.com/juliechevalier/GIANT/tree/master/galaxy/wrappers"
categories:
- "Micro-array Analysis"
- "Transcriptomics"
- "RNA"
- "Statistics"
- "Visualization"

description: "Galaxy-based Interactive tools for ANalysis of Transcriptomic data"
name: giant
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the GIANT tool: {{ tool_name }}"
suite:
  name: "suite_giant"
description: "Galaxy-based Interactive tools for ANalysis of Transcriptomic data"
